
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class LevelDialog
	{
		private global::Gtk.Frame frame_level_select;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Label label_level_id;

		private global::Gtk.ComboBox combobox_level_id;

		private global::Gtk.Entry text_level_id;

		private global::Gtk.Button btn_reload_level;

		private global::Gtk.Label label_level_range;

		private global::Gtk.Button btn_clear_data;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Frame frame_level_config;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox30;

		private global::Gtk.HBox hbox58;

		private global::Gtk.Frame frame_basic_config2;

		private global::Gtk.Alignment GtkAlignment13;

		private global::Gtk.HBox hbox28;

		private global::Gtk.VBox vbox19;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Label label14;

		private global::Gtk.ComboBox combobox_config_type;

		private global::Gtk.Label label21;

		private global::Gtk.Entry text_config_total;

		private global::Gtk.Label label23;

		private global::Gtk.Entry text_config_score;

		private global::Gtk.HBox hbox34;

		private global::Gtk.Label label25;

		private global::Gtk.Entry text_config_max_order;

		private global::Gtk.Label label27;

		private global::Gtk.Entry text_config_full_patience;

		private global::Gtk.HBox hbox36;

		private global::Gtk.Label label28;

		private global::Gtk.Entry text_config_order_interval_start;

		private global::Gtk.Label label29;

		private global::Gtk.Entry text_config_order_interval_end;

		private global::Gtk.Label label72;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Label label73;

		private global::Gtk.Entry text_config_first_arrivals;

		private global::Gtk.Label label_basic_config2;

		private global::Gtk.Frame frame_time_variables2;

		private global::Gtk.Alignment GtkAlignment14;

		private global::Gtk.HBox hbox38;

		private global::Gtk.VBox vbox24;

		private global::Gtk.HBox hbox41;

		private global::Gtk.Label label74;

		private global::Gtk.Label label75;

		private global::Gtk.Entry text_waitdecay_interval;

		private global::Gtk.Label label76;

		private global::Gtk.Entry text_waitdecay_rate;

		private global::Gtk.Label label_waitdecay_limit;

		private global::Gtk.Entry text_waitdecay_limit;

		private global::Gtk.HBox hbox45;

		private global::Gtk.Label label77;

		private global::Gtk.Label label78;

		private global::Gtk.Entry text_orderdecay_interval;

		private global::Gtk.Label label79;

		private global::Gtk.Entry text_orderdecay_rate;

		private global::Gtk.Label label_orderdecay_limit;

		private global::Gtk.Entry text_orderdecay_limit;

		private global::Gtk.HBox hbox49;

		private global::Gtk.Label label80;

		private global::Gtk.Label label81;

		private global::Gtk.Entry text_cookingdecay_interval;

		private global::Gtk.Label label82;

		private global::Gtk.Entry text_cookingdecay_rate;

		private global::Gtk.Label label_cookingdecay_limit;

		private global::Gtk.Entry text_cookingdecay_limit;

		private global::Gtk.VBox vbox26;

		private global::Gtk.HBox hbox43;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.Label label83;

		private global::Gtk.Label label84;

		private global::Gtk.Entry text_rainInterval_start;

		private global::Gtk.Label label85;

		private global::Gtk.Entry text_rainInterval_end;

		private global::Gtk.Label label_burndecay_limit;

		private global::Gtk.HBox hbox47;

		private global::Gtk.Alignment alignment17;

		private global::Gtk.Label label86;

		private global::Gtk.Label label87;

		private global::Gtk.Entry text_litterinterval_start;

		private global::Gtk.Label label88;

		private global::Gtk.Entry text_litterinterval_end;

		private global::Gtk.HBox hbox51;

		private global::Gtk.Alignment alignment19;

		private global::Gtk.Label label89;

		private global::Gtk.Label label90;

		private global::Gtk.Entry text_brokeninterval_start;

		private global::Gtk.Label label91;

		private global::Gtk.Entry text_brokeninterval_end;

		private global::Gtk.Label label92;

		private global::Gtk.Label label_time_variables2;

		private global::Gtk.Frame frame_conditions2;

		private global::Gtk.Alignment GtkAlignment15;

		private global::Gtk.VBox vbox28;

		private global::Gtk.HBox hbox53;

		private global::Gtk.HBox hbox55;

		private global::Gtk.Label label93;

		private global::Gtk.Entry text_secret_customers;

		private global::Gtk.VButtonBox vbuttonbox9;

		private global::Gtk.Button btn_config_secret_customers;

		private global::Gtk.Alignment alignment21;

		private global::Gtk.HBox hbox59;

		private global::Gtk.Label label94;

		private global::Gtk.Entry text_level_requirements;

		private global::Gtk.VButtonBox vbuttonbox8;

		private global::Gtk.Button btn_config_level_requirements;

		private global::Gtk.Alignment alignment23;

		private global::Gtk.HBox hbox60;

		private global::Gtk.Label label39;

		private global::Gtk.Entry text_min_instruct_steps;

		private global::Gtk.Alignment alignment32;

		private global::Gtk.HBox hbox79;

		private global::Gtk.Label label54;

		private global::Gtk.Entry text_unlock_item;

		private global::Gtk.Button button_edit_unlock_items;

		private global::Gtk.HBox hbox61;

		private global::Gtk.HBox hbox62;

		private global::Gtk.Label label95;

		private global::Gtk.ScrolledWindow GtkScrolledWindow5;

		private global::Gtk.TextView text_level_rewards;

		private global::Gtk.Button button_edit_rewards;

		private global::Gtk.Alignment alignment25;

		private global::Gtk.HBox hbox64;

		private global::Gtk.Label label41;

		private global::Gtk.ScrolledWindow GtkScrolledWindow3;

		private global::Gtk.TextView text_level_tips;

		private global::Gtk.VButtonBox vbuttonbox5;

		private global::Gtk.Button btn_config_level_tips;

		private global::Gtk.Alignment alignment28;

		private global::Gtk.HBox hbox77;

		private global::Gtk.Label label45;

		private global::Gtk.ScrolledWindow GtkScrolledWindow4;

		private global::Gtk.TextView text_level_comments;

		private global::Gtk.Label label_conditions2;

		private global::Gtk.Label label_level_config;

		private global::Gtk.Frame frame_available_orders;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Frame frame_foods;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tree_level_foods;

		private global::Gtk.Label label_foods;

		private global::Gtk.Frame frame_customers;

		private global::Gtk.Alignment GtkAlignment5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView tree_level_customer;

		private global::Gtk.Label label_customers;

		private global::Gtk.VButtonBox vbuttonbox3;

		private global::Gtk.Button btn_add_order;

		private global::Gtk.Button btn_remove_order;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Frame frame22;

		private global::Gtk.Alignment GtkAlignment6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TreeView tree_order_list;

		private global::Gtk.Label label_order_list;

		private global::Gtk.VButtonBox vbuttonbox_order_sequence;

		private global::Gtk.Button button_order_up;

		private global::Gtk.Button button_order_down;

		private global::Gtk.Button button_normalize_weight;

		private global::Gtk.Frame frame_auto_gen;

		private global::Gtk.Alignment GtkAlignment7;

		private global::Gtk.VBox vbox31;

		private global::Gtk.HBox hbox69;

		private global::Gtk.Label label_diffculty;

		private global::Gtk.ComboBox combobox_autogen_difficulty;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.Entry text_autogen_food_list;

		private global::Gtk.Button button_edit_autogen_food_list;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label4;

		private global::Gtk.Entry text_auto_customer_list;

		private global::Gtk.Button button_edit_autogen_customer_list;

		private global::Gtk.HBox hbox71;

		private global::Gtk.Label label48;

		private global::Gtk.Entry text_autogen_specialnum;

		private global::Gtk.Frame frame_auto_requirements;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox75;

		private global::Gtk.CheckButton check_autogen_random_customer;

		private global::Gtk.CheckButton check_autogen_random_food;

		private global::Gtk.HBox hbox9;

		private global::Gtk.CheckButton check_autogen_random_smile;

		private global::Gtk.CheckButton check_autogen_any_customer;

		private global::Gtk.Label GtkLabel22;

		private global::Gtk.VButtonBox vbuttonbox7;

		private global::Gtk.Button btn_autogen_generate;

		private global::Gtk.Button button_autogen_requirements;

		private global::Gtk.Label label_auto_gen1;

		private global::Gtk.Label Label_Available_Orders;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LevelEditor.LevelDialog
			this.Name = "LevelEditor.LevelDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("关卡编辑器");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			// Internal child LevelEditor.LevelDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame_level_select = new global::Gtk.Frame();
			this.frame_level_select.Name = "frame_level_select";
			this.frame_level_select.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_level_select.BorderWidth = ((uint)(5));
			// Container child frame_level_select.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label_level_id = new global::Gtk.Label();
			this.label_level_id.Name = "label_level_id";
			this.label_level_id.LabelProp = global::Mono.Unix.Catalog.GetString("关卡ID：");
			this.hbox19.Add(this.label_level_id);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.label_level_id]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.combobox_level_id = global::Gtk.ComboBox.NewText();
			this.combobox_level_id.Name = "combobox_level_id";
			this.hbox19.Add(this.combobox_level_id);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.combobox_level_id]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.text_level_id = new global::Gtk.Entry();
			this.text_level_id.WidthRequest = 100;
			this.text_level_id.CanFocus = true;
			this.text_level_id.Name = "text_level_id";
			this.text_level_id.IsEditable = true;
			this.hbox19.Add(this.text_level_id);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.text_level_id]));
			w4.Position = 2;
			w4.Expand = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btn_reload_level = new global::Gtk.Button();
			this.btn_reload_level.CanFocus = true;
			this.btn_reload_level.Name = "btn_reload_level";
			this.btn_reload_level.UseUnderline = true;
			this.btn_reload_level.Label = global::Mono.Unix.Catalog.GetString("加载关卡数据");
			this.hbox19.Add(this.btn_reload_level);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.btn_reload_level]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label_level_range = new global::Gtk.Label();
			this.label_level_range.Name = "label_level_range";
			this.label_level_range.LabelProp = global::Mono.Unix.Catalog.GetString("(关卡范围:xx-xx)");
			this.hbox19.Add(this.label_level_range);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.label_level_range]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btn_clear_data = new global::Gtk.Button();
			this.btn_clear_data.CanFocus = true;
			this.btn_clear_data.Name = "btn_clear_data";
			this.btn_clear_data.UseUnderline = true;
			this.btn_clear_data.Label = global::Mono.Unix.Catalog.GetString("清除数据");
			this.hbox19.Add(this.btn_clear_data);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.btn_clear_data]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			this.GtkAlignment2.Add(this.hbox19);
			this.frame_level_select.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>关卡选择</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame_level_select.LabelWidget = this.GtkLabel2;
			w1.Add(this.frame_level_select);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1[this.frame_level_select]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(5));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame_level_config = new global::Gtk.Frame();
			this.frame_level_config.Name = "frame_level_config";
			this.frame_level_config.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_level_config.BorderWidth = ((uint)(5));
			// Container child frame_level_config.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox30 = new global::Gtk.VBox();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			// Container child vbox30.Gtk.Box+BoxChild
			this.hbox58 = new global::Gtk.HBox();
			this.hbox58.Name = "hbox58";
			this.hbox58.Spacing = 6;
			// Container child hbox58.Gtk.Box+BoxChild
			this.frame_basic_config2 = new global::Gtk.Frame();
			this.frame_basic_config2.Name = "frame_basic_config2";
			this.frame_basic_config2.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_basic_config2.BorderWidth = ((uint)(1));
			// Container child frame_basic_config2.Gtk.Container+ContainerChild
			this.GtkAlignment13 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment13.Name = "GtkAlignment13";
			this.GtkAlignment13.LeftPadding = ((uint)(12));
			// Container child GtkAlignment13.Gtk.Container+ContainerChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("类型:");
			this.hbox29.Add(this.label14);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.label14]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.combobox_config_type = global::Gtk.ComboBox.NewText();
			this.combobox_config_type.AppendText(global::Mono.Unix.Catalog.GetString("固定时间"));
			this.combobox_config_type.AppendText(global::Mono.Unix.Catalog.GetString("固定人数"));
			this.combobox_config_type.AppendText(global::Mono.Unix.Catalog.GetString("流失"));
			this.combobox_config_type.Name = "combobox_config_type";
			this.combobox_config_type.Active = 0;
			this.hbox29.Add(this.combobox_config_type);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.combobox_config_type]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("参数:");
			this.hbox29.Add(this.label21);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.label21]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.text_config_total = new global::Gtk.Entry();
			this.text_config_total.WidthRequest = 50;
			this.text_config_total.CanFocus = true;
			this.text_config_total.Name = "text_config_total";
			this.text_config_total.IsEditable = true;
			this.hbox29.Add(this.text_config_total);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.text_config_total]));
			w14.Position = 3;
			// Container child hbox29.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("分数:");
			this.hbox29.Add(this.label23);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.label23]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.text_config_score = new global::Gtk.Entry();
			this.text_config_score.WidthRequest = 70;
			this.text_config_score.CanFocus = true;
			this.text_config_score.Name = "text_config_score";
			this.text_config_score.IsEditable = true;
			this.hbox29.Add(this.text_config_score);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.text_config_score]));
			w16.Position = 5;
			this.vbox19.Add(this.hbox29);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.hbox29]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("最大订单数:");
			this.hbox34.Add(this.label25);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.label25]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.text_config_max_order = new global::Gtk.Entry();
			this.text_config_max_order.WidthRequest = 20;
			this.text_config_max_order.CanFocus = true;
			this.text_config_max_order.Name = "text_config_max_order";
			this.text_config_max_order.IsEditable = true;
			this.hbox34.Add(this.text_config_max_order);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.text_config_max_order]));
			w19.Position = 1;
			// Container child hbox34.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("满耐心值:");
			this.hbox34.Add(this.label27);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.label27]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.text_config_full_patience = new global::Gtk.Entry();
			this.text_config_full_patience.WidthRequest = 50;
			this.text_config_full_patience.CanFocus = true;
			this.text_config_full_patience.Name = "text_config_full_patience";
			this.text_config_full_patience.IsEditable = true;
			this.hbox34.Add(this.text_config_full_patience);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.text_config_full_patience]));
			w21.Position = 3;
			this.vbox19.Add(this.hbox34);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.hbox34]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.hbox36 = new global::Gtk.HBox();
			this.hbox36.Name = "hbox36";
			this.hbox36.Spacing = 6;
			// Container child hbox36.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("订单间隔:");
			this.hbox36.Add(this.label28);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.label28]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.text_config_order_interval_start = new global::Gtk.Entry();
			this.text_config_order_interval_start.WidthRequest = 30;
			this.text_config_order_interval_start.CanFocus = true;
			this.text_config_order_interval_start.Name = "text_config_order_interval_start";
			this.text_config_order_interval_start.IsEditable = true;
			this.hbox36.Add(this.text_config_order_interval_start);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.text_config_order_interval_start]));
			w24.Position = 1;
			// Container child hbox36.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("到");
			this.hbox36.Add(this.label29);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.label29]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.text_config_order_interval_end = new global::Gtk.Entry();
			this.text_config_order_interval_end.WidthRequest = 30;
			this.text_config_order_interval_end.CanFocus = true;
			this.text_config_order_interval_end.Name = "text_config_order_interval_end";
			this.text_config_order_interval_end.IsEditable = true;
			this.hbox36.Add(this.text_config_order_interval_end);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.text_config_order_interval_end]));
			w26.Position = 3;
			// Container child hbox36.Gtk.Box+BoxChild
			this.label72 = new global::Gtk.Label();
			this.label72.Name = "label72";
			this.label72.LabelProp = global::Mono.Unix.Catalog.GetString("秒");
			this.hbox36.Add(this.label72);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.label72]));
			w27.Position = 4;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.alignment13.LeftPadding = ((uint)(10));
			// Container child alignment13.Gtk.Container+ContainerChild
			this.label73 = new global::Gtk.Label();
			this.label73.Name = "label73";
			this.label73.LabelProp = global::Mono.Unix.Catalog.GetString("首次来客时间:");
			this.alignment13.Add(this.label73);
			this.hbox36.Add(this.alignment13);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.alignment13]));
			w29.Position = 5;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.text_config_first_arrivals = new global::Gtk.Entry();
			this.text_config_first_arrivals.WidthRequest = 150;
			this.text_config_first_arrivals.CanFocus = true;
			this.text_config_first_arrivals.Name = "text_config_first_arrivals";
			this.text_config_first_arrivals.Text = global::Mono.Unix.Catalog.GetString("(逗号隔开，如2,5,8,11)");
			this.text_config_first_arrivals.IsEditable = true;
			this.hbox36.Add(this.text_config_first_arrivals);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox36[this.text_config_first_arrivals]));
			w30.Position = 6;
			this.vbox19.Add(this.hbox36);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.hbox36]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox28.Add(this.vbox19);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.vbox19]));
			w32.Position = 0;
			this.GtkAlignment13.Add(this.hbox28);
			this.frame_basic_config2.Add(this.GtkAlignment13);
			this.label_basic_config2 = new global::Gtk.Label();
			this.label_basic_config2.Name = "label_basic_config2";
			this.label_basic_config2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>基本配置</b>");
			this.label_basic_config2.UseMarkup = true;
			this.frame_basic_config2.LabelWidget = this.label_basic_config2;
			this.hbox58.Add(this.frame_basic_config2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox58[this.frame_basic_config2]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox58.Gtk.Box+BoxChild
			this.frame_time_variables2 = new global::Gtk.Frame();
			this.frame_time_variables2.Name = "frame_time_variables2";
			this.frame_time_variables2.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_time_variables2.BorderWidth = ((uint)(1));
			// Container child frame_time_variables2.Gtk.Container+ContainerChild
			this.GtkAlignment14 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment14.Name = "GtkAlignment14";
			this.GtkAlignment14.LeftPadding = ((uint)(12));
			// Container child GtkAlignment14.Gtk.Container+ContainerChild
			this.hbox38 = new global::Gtk.HBox();
			this.hbox38.Name = "hbox38";
			this.hbox38.Spacing = 6;
			// Container child hbox38.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox41 = new global::Gtk.HBox();
			this.hbox41.Name = "hbox41";
			this.hbox41.Spacing = 6;
			// Container child hbox41.Gtk.Box+BoxChild
			this.label74 = new global::Gtk.Label();
			this.label74.Name = "label74";
			this.label74.LabelProp = global::Mono.Unix.Catalog.GetString("等待时间衰减:");
			this.hbox41.Add(this.label74);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.label74]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox41.Gtk.Box+BoxChild
			this.label75 = new global::Gtk.Label();
			this.label75.Name = "label75";
			this.label75.LabelProp = global::Mono.Unix.Catalog.GetString("每");
			this.hbox41.Add(this.label75);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.label75]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox41.Gtk.Box+BoxChild
			this.text_waitdecay_interval = new global::Gtk.Entry();
			this.text_waitdecay_interval.WidthRequest = 30;
			this.text_waitdecay_interval.CanFocus = true;
			this.text_waitdecay_interval.Name = "text_waitdecay_interval";
			this.text_waitdecay_interval.IsEditable = true;
			this.hbox41.Add(this.text_waitdecay_interval);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.text_waitdecay_interval]));
			w38.Position = 2;
			// Container child hbox41.Gtk.Box+BoxChild
			this.label76 = new global::Gtk.Label();
			this.label76.Name = "label76";
			this.label76.LabelProp = global::Mono.Unix.Catalog.GetString("人衰减");
			this.hbox41.Add(this.label76);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.label76]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox41.Gtk.Box+BoxChild
			this.text_waitdecay_rate = new global::Gtk.Entry();
			this.text_waitdecay_rate.WidthRequest = 40;
			this.text_waitdecay_rate.CanFocus = true;
			this.text_waitdecay_rate.Name = "text_waitdecay_rate";
			this.text_waitdecay_rate.IsEditable = true;
			this.hbox41.Add(this.text_waitdecay_rate);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.text_waitdecay_rate]));
			w40.Position = 4;
			// Container child hbox41.Gtk.Box+BoxChild
			this.label_waitdecay_limit = new global::Gtk.Label();
			this.label_waitdecay_limit.Name = "label_waitdecay_limit";
			this.label_waitdecay_limit.LabelProp = global::Mono.Unix.Catalog.GetString("极限：");
			this.hbox41.Add(this.label_waitdecay_limit);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.label_waitdecay_limit]));
			w41.Position = 5;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox41.Gtk.Box+BoxChild
			this.text_waitdecay_limit = new global::Gtk.Entry();
			this.text_waitdecay_limit.WidthRequest = 40;
			this.text_waitdecay_limit.CanFocus = true;
			this.text_waitdecay_limit.Name = "text_waitdecay_limit";
			this.text_waitdecay_limit.IsEditable = true;
			this.hbox41.Add(this.text_waitdecay_limit);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.text_waitdecay_limit]));
			w42.Position = 6;
			this.vbox24.Add(this.hbox41);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox41]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox45 = new global::Gtk.HBox();
			this.hbox45.Name = "hbox45";
			this.hbox45.Spacing = 6;
			// Container child hbox45.Gtk.Box+BoxChild
			this.label77 = new global::Gtk.Label();
			this.label77.Name = "label77";
			this.label77.LabelProp = global::Mono.Unix.Catalog.GetString("来客时间衰减:");
			this.hbox45.Add(this.label77);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.label77]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox45.Gtk.Box+BoxChild
			this.label78 = new global::Gtk.Label();
			this.label78.Name = "label78";
			this.label78.LabelProp = global::Mono.Unix.Catalog.GetString("每");
			this.hbox45.Add(this.label78);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.label78]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox45.Gtk.Box+BoxChild
			this.text_orderdecay_interval = new global::Gtk.Entry();
			this.text_orderdecay_interval.WidthRequest = 30;
			this.text_orderdecay_interval.CanFocus = true;
			this.text_orderdecay_interval.Name = "text_orderdecay_interval";
			this.text_orderdecay_interval.IsEditable = true;
			this.hbox45.Add(this.text_orderdecay_interval);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.text_orderdecay_interval]));
			w46.Position = 2;
			// Container child hbox45.Gtk.Box+BoxChild
			this.label79 = new global::Gtk.Label();
			this.label79.Name = "label79";
			this.label79.LabelProp = global::Mono.Unix.Catalog.GetString("人衰减");
			this.hbox45.Add(this.label79);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.label79]));
			w47.Position = 3;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox45.Gtk.Box+BoxChild
			this.text_orderdecay_rate = new global::Gtk.Entry();
			this.text_orderdecay_rate.WidthRequest = 40;
			this.text_orderdecay_rate.CanFocus = true;
			this.text_orderdecay_rate.Name = "text_orderdecay_rate";
			this.text_orderdecay_rate.IsEditable = true;
			this.hbox45.Add(this.text_orderdecay_rate);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.text_orderdecay_rate]));
			w48.Position = 4;
			// Container child hbox45.Gtk.Box+BoxChild
			this.label_orderdecay_limit = new global::Gtk.Label();
			this.label_orderdecay_limit.Name = "label_orderdecay_limit";
			this.label_orderdecay_limit.LabelProp = global::Mono.Unix.Catalog.GetString("极限：");
			this.hbox45.Add(this.label_orderdecay_limit);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.label_orderdecay_limit]));
			w49.Position = 5;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox45.Gtk.Box+BoxChild
			this.text_orderdecay_limit = new global::Gtk.Entry();
			this.text_orderdecay_limit.WidthRequest = 40;
			this.text_orderdecay_limit.CanFocus = true;
			this.text_orderdecay_limit.Name = "text_orderdecay_limit";
			this.text_orderdecay_limit.IsEditable = true;
			this.hbox45.Add(this.text_orderdecay_limit);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.text_orderdecay_limit]));
			w50.Position = 6;
			this.vbox24.Add(this.hbox45);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox45]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox49 = new global::Gtk.HBox();
			this.hbox49.Name = "hbox49";
			this.hbox49.Spacing = 6;
			// Container child hbox49.Gtk.Box+BoxChild
			this.label80 = new global::Gtk.Label();
			this.label80.Name = "label80";
			this.label80.LabelProp = global::Mono.Unix.Catalog.GetString("制作时间衰减:");
			this.hbox49.Add(this.label80);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.label80]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox49.Gtk.Box+BoxChild
			this.label81 = new global::Gtk.Label();
			this.label81.Name = "label81";
			this.label81.LabelProp = global::Mono.Unix.Catalog.GetString("每");
			this.hbox49.Add(this.label81);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.label81]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox49.Gtk.Box+BoxChild
			this.text_cookingdecay_interval = new global::Gtk.Entry();
			this.text_cookingdecay_interval.WidthRequest = 30;
			this.text_cookingdecay_interval.CanFocus = true;
			this.text_cookingdecay_interval.Name = "text_cookingdecay_interval";
			this.text_cookingdecay_interval.IsEditable = true;
			this.hbox49.Add(this.text_cookingdecay_interval);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.text_cookingdecay_interval]));
			w54.Position = 2;
			// Container child hbox49.Gtk.Box+BoxChild
			this.label82 = new global::Gtk.Label();
			this.label82.Name = "label82";
			this.label82.LabelProp = global::Mono.Unix.Catalog.GetString("次衰减");
			this.hbox49.Add(this.label82);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.label82]));
			w55.Position = 3;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbox49.Gtk.Box+BoxChild
			this.text_cookingdecay_rate = new global::Gtk.Entry();
			this.text_cookingdecay_rate.WidthRequest = 40;
			this.text_cookingdecay_rate.CanFocus = true;
			this.text_cookingdecay_rate.Name = "text_cookingdecay_rate";
			this.text_cookingdecay_rate.IsEditable = true;
			this.hbox49.Add(this.text_cookingdecay_rate);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.text_cookingdecay_rate]));
			w56.Position = 4;
			// Container child hbox49.Gtk.Box+BoxChild
			this.label_cookingdecay_limit = new global::Gtk.Label();
			this.label_cookingdecay_limit.Name = "label_cookingdecay_limit";
			this.label_cookingdecay_limit.LabelProp = global::Mono.Unix.Catalog.GetString("极限：");
			this.hbox49.Add(this.label_cookingdecay_limit);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.label_cookingdecay_limit]));
			w57.Position = 5;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox49.Gtk.Box+BoxChild
			this.text_cookingdecay_limit = new global::Gtk.Entry();
			this.text_cookingdecay_limit.WidthRequest = 40;
			this.text_cookingdecay_limit.CanFocus = true;
			this.text_cookingdecay_limit.Name = "text_cookingdecay_limit";
			this.text_cookingdecay_limit.IsEditable = true;
			this.hbox49.Add(this.text_cookingdecay_limit);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.text_cookingdecay_limit]));
			w58.Position = 6;
			this.vbox24.Add(this.hbox49);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox49]));
			w59.Position = 2;
			w59.Expand = false;
			w59.Fill = false;
			this.hbox38.Add(this.vbox24);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox38[this.vbox24]));
			w60.Position = 0;
			// Container child hbox38.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox43 = new global::Gtk.HBox();
			this.hbox43.Name = "hbox43";
			this.hbox43.Spacing = 6;
			// Container child hbox43.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			this.alignment15.LeftPadding = ((uint)(20));
			// Container child alignment15.Gtk.Container+ContainerChild
			this.label83 = new global::Gtk.Label();
			this.label83.Name = "label83";
			this.label83.LabelProp = global::Mono.Unix.Catalog.GetString("下雨时间间隔：");
			this.alignment15.Add(this.label83);
			this.hbox43.Add(this.alignment15);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.alignment15]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hbox43.Gtk.Box+BoxChild
			this.label84 = new global::Gtk.Label();
			this.label84.Name = "label84";
			this.label84.LabelProp = global::Mono.Unix.Catalog.GetString("每");
			this.hbox43.Add(this.label84);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.label84]));
			w63.Position = 1;
			w63.Expand = false;
			w63.Fill = false;
			// Container child hbox43.Gtk.Box+BoxChild
			this.text_rainInterval_start = new global::Gtk.Entry();
			this.text_rainInterval_start.WidthRequest = 40;
			this.text_rainInterval_start.CanFocus = true;
			this.text_rainInterval_start.Name = "text_rainInterval_start";
			this.text_rainInterval_start.IsEditable = true;
			this.hbox43.Add(this.text_rainInterval_start);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.text_rainInterval_start]));
			w64.Position = 2;
			// Container child hbox43.Gtk.Box+BoxChild
			this.label85 = new global::Gtk.Label();
			this.label85.Name = "label85";
			this.label85.LabelProp = global::Mono.Unix.Catalog.GetString("秒至");
			this.hbox43.Add(this.label85);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.label85]));
			w65.Position = 3;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox43.Gtk.Box+BoxChild
			this.text_rainInterval_end = new global::Gtk.Entry();
			this.text_rainInterval_end.WidthRequest = 40;
			this.text_rainInterval_end.CanFocus = true;
			this.text_rainInterval_end.Name = "text_rainInterval_end";
			this.text_rainInterval_end.IsEditable = true;
			this.hbox43.Add(this.text_rainInterval_end);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.text_rainInterval_end]));
			w66.Position = 4;
			// Container child hbox43.Gtk.Box+BoxChild
			this.label_burndecay_limit = new global::Gtk.Label();
			this.label_burndecay_limit.Name = "label_burndecay_limit";
			this.label_burndecay_limit.LabelProp = global::Mono.Unix.Catalog.GetString("秒下雨");
			this.hbox43.Add(this.label_burndecay_limit);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.label_burndecay_limit]));
			w67.Position = 5;
			w67.Expand = false;
			w67.Fill = false;
			this.vbox26.Add(this.hbox43);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox43]));
			w68.Position = 0;
			w68.Expand = false;
			w68.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox47 = new global::Gtk.HBox();
			this.hbox47.Name = "hbox47";
			this.hbox47.Spacing = 6;
			// Container child hbox47.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			this.alignment17.LeftPadding = ((uint)(20));
			// Container child alignment17.Gtk.Container+ContainerChild
			this.label86 = new global::Gtk.Label();
			this.label86.Name = "label86";
			this.label86.LabelProp = global::Mono.Unix.Catalog.GetString("扔垃圾间隔:");
			this.alignment17.Add(this.label86);
			this.hbox47.Add(this.alignment17);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.alignment17]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox47.Gtk.Box+BoxChild
			this.label87 = new global::Gtk.Label();
			this.label87.Name = "label87";
			this.label87.LabelProp = global::Mono.Unix.Catalog.GetString("每");
			this.hbox47.Add(this.label87);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.label87]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			// Container child hbox47.Gtk.Box+BoxChild
			this.text_litterinterval_start = new global::Gtk.Entry();
			this.text_litterinterval_start.WidthRequest = 30;
			this.text_litterinterval_start.CanFocus = true;
			this.text_litterinterval_start.Name = "text_litterinterval_start";
			this.text_litterinterval_start.IsEditable = true;
			this.hbox47.Add(this.text_litterinterval_start);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.text_litterinterval_start]));
			w72.Position = 2;
			// Container child hbox47.Gtk.Box+BoxChild
			this.label88 = new global::Gtk.Label();
			this.label88.Name = "label88";
			this.label88.LabelProp = global::Mono.Unix.Catalog.GetString("人至");
			this.hbox47.Add(this.label88);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.label88]));
			w73.Position = 3;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox47.Gtk.Box+BoxChild
			this.text_litterinterval_end = new global::Gtk.Entry();
			this.text_litterinterval_end.WidthRequest = 40;
			this.text_litterinterval_end.CanFocus = true;
			this.text_litterinterval_end.Name = "text_litterinterval_end";
			this.text_litterinterval_end.IsEditable = true;
			this.hbox47.Add(this.text_litterinterval_end);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.text_litterinterval_end]));
			w74.Position = 4;
			this.vbox26.Add(this.hbox47);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox47]));
			w75.Position = 1;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox51 = new global::Gtk.HBox();
			this.hbox51.Name = "hbox51";
			this.hbox51.Spacing = 6;
			// Container child hbox51.Gtk.Box+BoxChild
			this.alignment19 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment19.Name = "alignment19";
			this.alignment19.LeftPadding = ((uint)(20));
			// Container child alignment19.Gtk.Container+ContainerChild
			this.label89 = new global::Gtk.Label();
			this.label89.Name = "label89";
			this.label89.LabelProp = global::Mono.Unix.Catalog.GetString("厨具损坏间隔:");
			this.alignment19.Add(this.label89);
			this.hbox51.Add(this.alignment19);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.alignment19]));
			w77.Position = 0;
			w77.Expand = false;
			w77.Fill = false;
			// Container child hbox51.Gtk.Box+BoxChild
			this.label90 = new global::Gtk.Label();
			this.label90.Name = "label90";
			this.label90.LabelProp = global::Mono.Unix.Catalog.GetString("每使用");
			this.hbox51.Add(this.label90);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.label90]));
			w78.Position = 1;
			w78.Expand = false;
			w78.Fill = false;
			// Container child hbox51.Gtk.Box+BoxChild
			this.text_brokeninterval_start = new global::Gtk.Entry();
			this.text_brokeninterval_start.WidthRequest = 30;
			this.text_brokeninterval_start.CanFocus = true;
			this.text_brokeninterval_start.Name = "text_brokeninterval_start";
			this.text_brokeninterval_start.IsEditable = true;
			this.hbox51.Add(this.text_brokeninterval_start);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.text_brokeninterval_start]));
			w79.Position = 2;
			// Container child hbox51.Gtk.Box+BoxChild
			this.label91 = new global::Gtk.Label();
			this.label91.Name = "label91";
			this.label91.LabelProp = global::Mono.Unix.Catalog.GetString("至");
			this.hbox51.Add(this.label91);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.label91]));
			w80.Position = 3;
			w80.Expand = false;
			w80.Fill = false;
			// Container child hbox51.Gtk.Box+BoxChild
			this.text_brokeninterval_end = new global::Gtk.Entry();
			this.text_brokeninterval_end.WidthRequest = 40;
			this.text_brokeninterval_end.CanFocus = true;
			this.text_brokeninterval_end.Name = "text_brokeninterval_end";
			this.text_brokeninterval_end.IsEditable = true;
			this.hbox51.Add(this.text_brokeninterval_end);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.text_brokeninterval_end]));
			w81.Position = 4;
			// Container child hbox51.Gtk.Box+BoxChild
			this.label92 = new global::Gtk.Label();
			this.label92.Name = "label92";
			this.label92.LabelProp = global::Mono.Unix.Catalog.GetString("次");
			this.hbox51.Add(this.label92);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.label92]));
			w82.Position = 5;
			w82.Expand = false;
			w82.Fill = false;
			this.vbox26.Add(this.hbox51);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.hbox51]));
			w83.Position = 2;
			w83.Expand = false;
			w83.Fill = false;
			this.hbox38.Add(this.vbox26);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox38[this.vbox26]));
			w84.Position = 1;
			this.GtkAlignment14.Add(this.hbox38);
			this.frame_time_variables2.Add(this.GtkAlignment14);
			this.label_time_variables2 = new global::Gtk.Label();
			this.label_time_variables2.Name = "label_time_variables2";
			this.label_time_variables2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>时间变量</b>");
			this.label_time_variables2.UseMarkup = true;
			this.frame_time_variables2.LabelWidget = this.label_time_variables2;
			this.hbox58.Add(this.frame_time_variables2);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox58[this.frame_time_variables2]));
			w87.PackType = ((global::Gtk.PackType)(1));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			w87.Padding = ((uint)(10));
			this.vbox30.Add(this.hbox58);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.hbox58]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.frame_conditions2 = new global::Gtk.Frame();
			this.frame_conditions2.Name = "frame_conditions2";
			this.frame_conditions2.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_conditions2.BorderWidth = ((uint)(1));
			// Container child frame_conditions2.Gtk.Container+ContainerChild
			this.GtkAlignment15 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment15.Name = "GtkAlignment15";
			this.GtkAlignment15.LeftPadding = ((uint)(12));
			// Container child GtkAlignment15.Gtk.Container+ContainerChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox53 = new global::Gtk.HBox();
			this.hbox53.Name = "hbox53";
			this.hbox53.Spacing = 6;
			// Container child hbox53.Gtk.Box+BoxChild
			this.hbox55 = new global::Gtk.HBox();
			this.hbox55.Name = "hbox55";
			this.hbox55.Spacing = 6;
			// Container child hbox55.Gtk.Box+BoxChild
			this.label93 = new global::Gtk.Label();
			this.label93.Name = "label93";
			this.label93.LabelProp = global::Mono.Unix.Catalog.GetString("神秘顾客:");
			this.hbox55.Add(this.label93);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox55[this.label93]));
			w89.Position = 0;
			w89.Expand = false;
			w89.Fill = false;
			// Container child hbox55.Gtk.Box+BoxChild
			this.text_secret_customers = new global::Gtk.Entry();
			this.text_secret_customers.WidthRequest = 150;
			this.text_secret_customers.CanFocus = true;
			this.text_secret_customers.Name = "text_secret_customers";
			this.text_secret_customers.IsEditable = false;
			this.hbox55.Add(this.text_secret_customers);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox55[this.text_secret_customers]));
			w90.Position = 1;
			w90.Expand = false;
			// Container child hbox55.Gtk.Box+BoxChild
			this.vbuttonbox9 = new global::Gtk.VButtonBox();
			this.vbuttonbox9.Name = "vbuttonbox9";
			// Container child vbuttonbox9.Gtk.ButtonBox+ButtonBoxChild
			this.btn_config_secret_customers = new global::Gtk.Button();
			this.btn_config_secret_customers.CanFocus = true;
			this.btn_config_secret_customers.Name = "btn_config_secret_customers";
			this.btn_config_secret_customers.UseUnderline = true;
			this.btn_config_secret_customers.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.vbuttonbox9.Add(this.btn_config_secret_customers);
			global::Gtk.ButtonBox.ButtonBoxChild w91 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox9[this.btn_config_secret_customers]));
			w91.Expand = false;
			w91.Fill = false;
			this.hbox55.Add(this.vbuttonbox9);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox55[this.vbuttonbox9]));
			w92.Position = 2;
			w92.Expand = false;
			w92.Fill = false;
			this.hbox53.Add(this.hbox55);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.hbox55]));
			w93.Position = 0;
			w93.Expand = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment21.Name = "alignment21";
			this.alignment21.LeftPadding = ((uint)(10));
			// Container child alignment21.Gtk.Container+ContainerChild
			this.hbox59 = new global::Gtk.HBox();
			this.hbox59.Name = "hbox59";
			this.hbox59.Spacing = 6;
			// Container child hbox59.Gtk.Box+BoxChild
			this.label94 = new global::Gtk.Label();
			this.label94.Name = "label94";
			this.label94.LabelProp = global::Mono.Unix.Catalog.GetString("过关条件:");
			this.hbox59.Add(this.label94);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox59[this.label94]));
			w94.Position = 0;
			w94.Expand = false;
			w94.Fill = false;
			// Container child hbox59.Gtk.Box+BoxChild
			this.text_level_requirements = new global::Gtk.Entry();
			this.text_level_requirements.WidthRequest = 200;
			this.text_level_requirements.CanFocus = true;
			this.text_level_requirements.Name = "text_level_requirements";
			this.text_level_requirements.IsEditable = false;
			this.hbox59.Add(this.text_level_requirements);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox59[this.text_level_requirements]));
			w95.Position = 1;
			w95.Expand = false;
			// Container child hbox59.Gtk.Box+BoxChild
			this.vbuttonbox8 = new global::Gtk.VButtonBox();
			this.vbuttonbox8.Name = "vbuttonbox8";
			// Container child vbuttonbox8.Gtk.ButtonBox+ButtonBoxChild
			this.btn_config_level_requirements = new global::Gtk.Button();
			this.btn_config_level_requirements.CanFocus = true;
			this.btn_config_level_requirements.Name = "btn_config_level_requirements";
			this.btn_config_level_requirements.UseUnderline = true;
			this.btn_config_level_requirements.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.vbuttonbox8.Add(this.btn_config_level_requirements);
			global::Gtk.ButtonBox.ButtonBoxChild w96 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox8[this.btn_config_level_requirements]));
			w96.Expand = false;
			w96.Fill = false;
			this.hbox59.Add(this.vbuttonbox8);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox59[this.vbuttonbox8]));
			w97.Position = 2;
			w97.Expand = false;
			w97.Fill = false;
			this.alignment21.Add(this.hbox59);
			this.hbox53.Add(this.alignment21);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.alignment21]));
			w99.Position = 1;
			w99.Expand = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.alignment23 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment23.Name = "alignment23";
			this.alignment23.LeftPadding = ((uint)(20));
			// Container child alignment23.Gtk.Container+ContainerChild
			this.hbox60 = new global::Gtk.HBox();
			this.hbox60.Name = "hbox60";
			this.hbox60.Spacing = 6;
			// Container child hbox60.Gtk.Box+BoxChild
			this.label39 = new global::Gtk.Label();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("最小提示制作步数:");
			this.hbox60.Add(this.label39);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox60[this.label39]));
			w100.Position = 0;
			w100.Expand = false;
			w100.Fill = false;
			// Container child hbox60.Gtk.Box+BoxChild
			this.text_min_instruct_steps = new global::Gtk.Entry();
			this.text_min_instruct_steps.WidthRequest = 50;
			this.text_min_instruct_steps.CanFocus = true;
			this.text_min_instruct_steps.Name = "text_min_instruct_steps";
			this.text_min_instruct_steps.IsEditable = true;
			this.hbox60.Add(this.text_min_instruct_steps);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox60[this.text_min_instruct_steps]));
			w101.Position = 1;
			w101.Expand = false;
			this.alignment23.Add(this.hbox60);
			this.hbox53.Add(this.alignment23);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.alignment23]));
			w103.Position = 2;
			w103.Expand = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.alignment32 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment32.Name = "alignment32";
			this.alignment32.LeftPadding = ((uint)(20));
			// Container child alignment32.Gtk.Container+ContainerChild
			this.hbox79 = new global::Gtk.HBox();
			this.hbox79.Name = "hbox79";
			this.hbox79.Spacing = 6;
			// Container child hbox79.Gtk.Box+BoxChild
			this.label54 = new global::Gtk.Label();
			this.label54.Name = "label54";
			this.label54.LabelProp = global::Mono.Unix.Catalog.GetString("解锁物品:");
			this.hbox79.Add(this.label54);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox79[this.label54]));
			w104.Position = 0;
			w104.Expand = false;
			w104.Fill = false;
			// Container child hbox79.Gtk.Box+BoxChild
			this.text_unlock_item = new global::Gtk.Entry();
			this.text_unlock_item.WidthRequest = 200;
			this.text_unlock_item.CanFocus = true;
			this.text_unlock_item.Name = "text_unlock_item";
			this.text_unlock_item.IsEditable = false;
			this.hbox79.Add(this.text_unlock_item);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox79[this.text_unlock_item]));
			w105.Position = 1;
			w105.Expand = false;
			// Container child hbox79.Gtk.Box+BoxChild
			this.button_edit_unlock_items = new global::Gtk.Button();
			this.button_edit_unlock_items.WidthRequest = 80;
			this.button_edit_unlock_items.CanFocus = true;
			this.button_edit_unlock_items.Name = "button_edit_unlock_items";
			this.button_edit_unlock_items.UseUnderline = true;
			this.button_edit_unlock_items.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.hbox79.Add(this.button_edit_unlock_items);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox79[this.button_edit_unlock_items]));
			w106.Position = 2;
			w106.Expand = false;
			w106.Fill = false;
			this.alignment32.Add(this.hbox79);
			this.hbox53.Add(this.alignment32);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.alignment32]));
			w108.Position = 3;
			this.vbox28.Add(this.hbox53);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox53]));
			w109.Position = 0;
			w109.Expand = false;
			w109.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.hbox61 = new global::Gtk.HBox();
			this.hbox61.Name = "hbox61";
			this.hbox61.Spacing = 6;
			// Container child hbox61.Gtk.Box+BoxChild
			this.hbox62 = new global::Gtk.HBox();
			this.hbox62.Name = "hbox62";
			this.hbox62.Spacing = 6;
			// Container child hbox62.Gtk.Box+BoxChild
			this.label95 = new global::Gtk.Label();
			this.label95.Name = "label95";
			this.label95.LabelProp = global::Mono.Unix.Catalog.GetString("过关奖励:");
			this.hbox62.Add(this.label95);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox62[this.label95]));
			w110.Position = 0;
			w110.Expand = false;
			w110.Fill = false;
			// Container child hbox62.Gtk.Box+BoxChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.text_level_rewards = new global::Gtk.TextView();
			this.text_level_rewards.WidthRequest = 200;
			this.text_level_rewards.CanFocus = true;
			this.text_level_rewards.Name = "text_level_rewards";
			this.GtkScrolledWindow5.Add(this.text_level_rewards);
			this.hbox62.Add(this.GtkScrolledWindow5);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox62[this.GtkScrolledWindow5]));
			w112.Position = 1;
			// Container child hbox62.Gtk.Box+BoxChild
			this.button_edit_rewards = new global::Gtk.Button();
			this.button_edit_rewards.WidthRequest = 80;
			this.button_edit_rewards.CanFocus = true;
			this.button_edit_rewards.Name = "button_edit_rewards";
			this.button_edit_rewards.UseUnderline = true;
			this.button_edit_rewards.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.hbox62.Add(this.button_edit_rewards);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox62[this.button_edit_rewards]));
			w113.Position = 2;
			w113.Expand = false;
			w113.Fill = false;
			this.hbox61.Add(this.hbox62);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox61[this.hbox62]));
			w114.Position = 0;
			w114.Expand = false;
			// Container child hbox61.Gtk.Box+BoxChild
			this.alignment25 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment25.Name = "alignment25";
			this.alignment25.LeftPadding = ((uint)(20));
			// Container child alignment25.Gtk.Container+ContainerChild
			this.hbox64 = new global::Gtk.HBox();
			this.hbox64.Name = "hbox64";
			this.hbox64.Spacing = 6;
			// Container child hbox64.Gtk.Box+BoxChild
			this.label41 = new global::Gtk.Label();
			this.label41.Name = "label41";
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("过关提示:");
			this.hbox64.Add(this.label41);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox64[this.label41]));
			w115.Position = 0;
			w115.Expand = false;
			w115.Fill = false;
			// Container child hbox64.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow3.WidthRequest = 250;
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.text_level_tips = new global::Gtk.TextView();
			this.text_level_tips.CanFocus = true;
			this.text_level_tips.Name = "text_level_tips";
			this.text_level_tips.Editable = false;
			this.GtkScrolledWindow3.Add(this.text_level_tips);
			this.hbox64.Add(this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox64[this.GtkScrolledWindow3]));
			w117.Position = 1;
			w117.Expand = false;
			// Container child hbox64.Gtk.Box+BoxChild
			this.vbuttonbox5 = new global::Gtk.VButtonBox();
			this.vbuttonbox5.Name = "vbuttonbox5";
			// Container child vbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
			this.btn_config_level_tips = new global::Gtk.Button();
			this.btn_config_level_tips.CanFocus = true;
			this.btn_config_level_tips.Name = "btn_config_level_tips";
			this.btn_config_level_tips.UseUnderline = true;
			this.btn_config_level_tips.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.vbuttonbox5.Add(this.btn_config_level_tips);
			global::Gtk.ButtonBox.ButtonBoxChild w118 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox5[this.btn_config_level_tips]));
			w118.Expand = false;
			w118.Fill = false;
			this.hbox64.Add(this.vbuttonbox5);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox64[this.vbuttonbox5]));
			w119.Position = 2;
			w119.Expand = false;
			w119.Fill = false;
			// Container child hbox64.Gtk.Box+BoxChild
			this.alignment28 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment28.Name = "alignment28";
			this.alignment28.LeftPadding = ((uint)(20));
			// Container child alignment28.Gtk.Container+ContainerChild
			this.hbox77 = new global::Gtk.HBox();
			this.hbox77.Name = "hbox77";
			this.hbox77.Spacing = 6;
			// Container child hbox77.Gtk.Box+BoxChild
			this.label45 = new global::Gtk.Label();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("备注:");
			this.hbox77.Add(this.label45);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbox77[this.label45]));
			w120.Position = 0;
			w120.Expand = false;
			w120.Fill = false;
			// Container child hbox77.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.text_level_comments = new global::Gtk.TextView();
			this.text_level_comments.WidthRequest = 300;
			this.text_level_comments.HeightRequest = 50;
			this.text_level_comments.CanFocus = true;
			this.text_level_comments.Name = "text_level_comments";
			this.GtkScrolledWindow4.Add(this.text_level_comments);
			this.hbox77.Add(this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox77[this.GtkScrolledWindow4]));
			w122.Position = 1;
			this.alignment28.Add(this.hbox77);
			this.hbox64.Add(this.alignment28);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.hbox64[this.alignment28]));
			w124.PackType = ((global::Gtk.PackType)(1));
			w124.Position = 3;
			this.alignment25.Add(this.hbox64);
			this.hbox61.Add(this.alignment25);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox61[this.alignment25]));
			w126.Position = 1;
			this.vbox28.Add(this.hbox61);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.hbox61]));
			w127.Position = 1;
			w127.Expand = false;
			w127.Fill = false;
			this.GtkAlignment15.Add(this.vbox28);
			this.frame_conditions2.Add(this.GtkAlignment15);
			this.label_conditions2 = new global::Gtk.Label();
			this.label_conditions2.Name = "label_conditions2";
			this.label_conditions2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>过关相关</b>");
			this.label_conditions2.UseMarkup = true;
			this.frame_conditions2.LabelWidget = this.label_conditions2;
			this.vbox30.Add(this.frame_conditions2);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.frame_conditions2]));
			w130.Position = 1;
			w130.Expand = false;
			w130.Fill = false;
			this.GtkAlignment.Add(this.vbox30);
			this.frame_level_config.Add(this.GtkAlignment);
			this.label_level_config = new global::Gtk.Label();
			this.label_level_config.Name = "label_level_config";
			this.label_level_config.LabelProp = global::Mono.Unix.Catalog.GetString("<b>关卡配置</b>");
			this.label_level_config.UseMarkup = true;
			this.frame_level_config.LabelWidget = this.label_level_config;
			w1.Add(this.frame_level_config);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(w1[this.frame_level_config]));
			w133.Position = 1;
			w133.Expand = false;
			w133.Fill = false;
			w133.Padding = ((uint)(5));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame_available_orders = new global::Gtk.Frame();
			this.frame_available_orders.Name = "frame_available_orders";
			this.frame_available_orders.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_available_orders.BorderWidth = ((uint)(5));
			// Container child frame_available_orders.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.frame_foods = new global::Gtk.Frame();
			this.frame_foods.Name = "frame_foods";
			this.frame_foods.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_foods.BorderWidth = ((uint)(1));
			// Container child frame_foods.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tree_level_foods = new global::Gtk.TreeView();
			this.tree_level_foods.WidthRequest = 150;
			this.tree_level_foods.HeightRequest = 400;
			this.tree_level_foods.CanFocus = true;
			this.tree_level_foods.Name = "tree_level_foods";
			this.GtkScrolledWindow.Add(this.tree_level_foods);
			this.GtkAlignment4.Add(this.GtkScrolledWindow);
			this.frame_foods.Add(this.GtkAlignment4);
			this.label_foods = new global::Gtk.Label();
			this.label_foods.Name = "label_foods";
			this.label_foods.LabelProp = global::Mono.Unix.Catalog.GetString("<b>选择食物</b>");
			this.label_foods.UseMarkup = true;
			this.frame_foods.LabelWidget = this.label_foods;
			this.hbox20.Add(this.frame_foods);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.frame_foods]));
			w137.Position = 0;
			w137.Expand = false;
			w137.Fill = false;
			w137.Padding = ((uint)(5));
			// Container child hbox20.Gtk.Box+BoxChild
			this.frame_customers = new global::Gtk.Frame();
			this.frame_customers.Name = "frame_customers";
			this.frame_customers.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_customers.BorderWidth = ((uint)(1));
			// Container child frame_customers.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tree_level_customer = new global::Gtk.TreeView();
			this.tree_level_customer.WidthRequest = 150;
			this.tree_level_customer.CanFocus = true;
			this.tree_level_customer.Name = "tree_level_customer";
			this.GtkScrolledWindow1.Add(this.tree_level_customer);
			this.GtkAlignment5.Add(this.GtkScrolledWindow1);
			this.frame_customers.Add(this.GtkAlignment5);
			this.label_customers = new global::Gtk.Label();
			this.label_customers.Name = "label_customers";
			this.label_customers.LabelProp = global::Mono.Unix.Catalog.GetString("<b>选择顾客</b>");
			this.label_customers.UseMarkup = true;
			this.frame_customers.LabelWidget = this.label_customers;
			this.hbox20.Add(this.frame_customers);
			global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.frame_customers]));
			w141.Position = 1;
			w141.Expand = false;
			w141.Fill = false;
			w141.Padding = ((uint)(5));
			// Container child hbox20.Gtk.Box+BoxChild
			this.vbuttonbox3 = new global::Gtk.VButtonBox();
			this.vbuttonbox3.Name = "vbuttonbox3";
			this.vbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btn_add_order = new global::Gtk.Button();
			this.btn_add_order.CanFocus = true;
			this.btn_add_order.Name = "btn_add_order";
			this.btn_add_order.UseUnderline = true;
			this.btn_add_order.Label = global::Mono.Unix.Catalog.GetString(">>>>");
			this.vbuttonbox3.Add(this.btn_add_order);
			global::Gtk.ButtonBox.ButtonBoxChild w142 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3[this.btn_add_order]));
			w142.Expand = false;
			w142.Fill = false;
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btn_remove_order = new global::Gtk.Button();
			this.btn_remove_order.CanFocus = true;
			this.btn_remove_order.Name = "btn_remove_order";
			this.btn_remove_order.UseUnderline = true;
			this.btn_remove_order.Label = global::Mono.Unix.Catalog.GetString("<<<<");
			this.vbuttonbox3.Add(this.btn_remove_order);
			global::Gtk.ButtonBox.ButtonBoxChild w143 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3[this.btn_remove_order]));
			w143.Position = 1;
			w143.Expand = false;
			w143.Fill = false;
			this.hbox20.Add(this.vbuttonbox3);
			global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.vbuttonbox3]));
			w144.Position = 2;
			w144.Expand = false;
			w144.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame22 = new global::Gtk.Frame();
			this.frame22.Name = "frame22";
			this.frame22.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame22.BorderWidth = ((uint)(1));
			// Container child frame22.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.tree_order_list = new global::Gtk.TreeView();
			this.tree_order_list.WidthRequest = 360;
			this.tree_order_list.CanFocus = true;
			this.tree_order_list.Name = "tree_order_list";
			this.GtkScrolledWindow2.Add(this.tree_order_list);
			this.GtkAlignment6.Add(this.GtkScrolledWindow2);
			this.frame22.Add(this.GtkAlignment6);
			this.label_order_list = new global::Gtk.Label();
			this.label_order_list.Name = "label_order_list";
			this.label_order_list.LabelProp = global::Mono.Unix.Catalog.GetString("<b>订单列表</b>");
			this.label_order_list.UseMarkup = true;
			this.frame22.LabelWidget = this.label_order_list;
			this.hbox1.Add(this.frame22);
			global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame22]));
			w148.Position = 0;
			w148.Expand = false;
			w148.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox_order_sequence = new global::Gtk.VButtonBox();
			this.vbuttonbox_order_sequence.Name = "vbuttonbox_order_sequence";
			this.vbuttonbox_order_sequence.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox_order_sequence.Gtk.ButtonBox+ButtonBoxChild
			this.button_order_up = new global::Gtk.Button();
			this.button_order_up.HeightRequest = 50;
			this.button_order_up.CanFocus = true;
			this.button_order_up.Name = "button_order_up";
			this.button_order_up.UseUnderline = true;
			this.button_order_up.Label = global::Mono.Unix.Catalog.GetString("上移(⇧)");
			this.vbuttonbox_order_sequence.Add(this.button_order_up);
			global::Gtk.ButtonBox.ButtonBoxChild w149 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox_order_sequence[this.button_order_up]));
			w149.Expand = false;
			w149.Fill = false;
			// Container child vbuttonbox_order_sequence.Gtk.ButtonBox+ButtonBoxChild
			this.button_order_down = new global::Gtk.Button();
			this.button_order_down.HeightRequest = 50;
			this.button_order_down.CanFocus = true;
			this.button_order_down.Name = "button_order_down";
			this.button_order_down.UseUnderline = true;
			this.button_order_down.Label = global::Mono.Unix.Catalog.GetString("下移(⇩)");
			this.vbuttonbox_order_sequence.Add(this.button_order_down);
			global::Gtk.ButtonBox.ButtonBoxChild w150 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox_order_sequence[this.button_order_down]));
			w150.Position = 1;
			w150.Expand = false;
			w150.Fill = false;
			// Container child vbuttonbox_order_sequence.Gtk.ButtonBox+ButtonBoxChild
			this.button_normalize_weight = new global::Gtk.Button();
			this.button_normalize_weight.CanFocus = true;
			this.button_normalize_weight.Name = "button_normalize_weight";
			this.button_normalize_weight.UseUnderline = true;
			this.button_normalize_weight.Label = global::Mono.Unix.Catalog.GetString("归一化比重");
			this.vbuttonbox_order_sequence.Add(this.button_normalize_weight);
			global::Gtk.ButtonBox.ButtonBoxChild w151 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox_order_sequence[this.button_normalize_weight]));
			w151.Position = 2;
			w151.Expand = false;
			w151.Fill = false;
			this.hbox1.Add(this.vbuttonbox_order_sequence);
			global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox_order_sequence]));
			w152.Position = 1;
			w152.Expand = false;
			w152.Fill = false;
			this.hbox20.Add(this.hbox1);
			global::Gtk.Box.BoxChild w153 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.hbox1]));
			w153.Position = 3;
			w153.Expand = false;
			w153.Fill = false;
			w153.Padding = ((uint)(5));
			// Container child hbox20.Gtk.Box+BoxChild
			this.frame_auto_gen = new global::Gtk.Frame();
			this.frame_auto_gen.Name = "frame_auto_gen";
			this.frame_auto_gen.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame_auto_gen.BorderWidth = ((uint)(1));
			// Container child frame_auto_gen.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.vbox31 = new global::Gtk.VBox();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox69 = new global::Gtk.HBox();
			this.hbox69.Name = "hbox69";
			this.hbox69.Spacing = 6;
			// Container child hbox69.Gtk.Box+BoxChild
			this.label_diffculty = new global::Gtk.Label();
			this.label_diffculty.Name = "label_diffculty";
			this.label_diffculty.LabelProp = global::Mono.Unix.Catalog.GetString("难度：");
			this.hbox69.Add(this.label_diffculty);
			global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.hbox69[this.label_diffculty]));
			w154.Position = 0;
			w154.Expand = false;
			w154.Fill = false;
			// Container child hbox69.Gtk.Box+BoxChild
			this.combobox_autogen_difficulty = global::Gtk.ComboBox.NewText();
			this.combobox_autogen_difficulty.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.combobox_autogen_difficulty.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.combobox_autogen_difficulty.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.combobox_autogen_difficulty.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.combobox_autogen_difficulty.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.combobox_autogen_difficulty.Name = "combobox_autogen_difficulty";
			this.combobox_autogen_difficulty.Active = 0;
			this.hbox69.Add(this.combobox_autogen_difficulty);
			global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(this.hbox69[this.combobox_autogen_difficulty]));
			w155.Position = 1;
			w155.Expand = false;
			w155.Fill = false;
			this.vbox31.Add(this.hbox69);
			global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox69]));
			w156.Position = 0;
			w156.Expand = false;
			w156.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("食物集：");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w157.Position = 0;
			w157.Expand = false;
			w157.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.text_autogen_food_list = new global::Gtk.Entry();
			this.text_autogen_food_list.CanFocus = true;
			this.text_autogen_food_list.Name = "text_autogen_food_list";
			this.text_autogen_food_list.IsEditable = true;
			this.hbox5.Add(this.text_autogen_food_list);
			global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.text_autogen_food_list]));
			w158.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button_edit_autogen_food_list = new global::Gtk.Button();
			this.button_edit_autogen_food_list.CanFocus = true;
			this.button_edit_autogen_food_list.Name = "button_edit_autogen_food_list";
			this.button_edit_autogen_food_list.UseUnderline = true;
			this.button_edit_autogen_food_list.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.hbox5.Add(this.button_edit_autogen_food_list);
			global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button_edit_autogen_food_list]));
			w159.Position = 2;
			w159.Expand = false;
			w159.Fill = false;
			this.vbox31.Add(this.hbox5);
			global::Gtk.Box.BoxChild w160 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox5]));
			w160.Position = 1;
			w160.Expand = false;
			w160.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("顾客集：");
			this.hbox7.Add(this.label4);
			global::Gtk.Box.BoxChild w161 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label4]));
			w161.Position = 0;
			w161.Expand = false;
			w161.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.text_auto_customer_list = new global::Gtk.Entry();
			this.text_auto_customer_list.CanFocus = true;
			this.text_auto_customer_list.Name = "text_auto_customer_list";
			this.text_auto_customer_list.IsEditable = true;
			this.hbox7.Add(this.text_auto_customer_list);
			global::Gtk.Box.BoxChild w162 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.text_auto_customer_list]));
			w162.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button_edit_autogen_customer_list = new global::Gtk.Button();
			this.button_edit_autogen_customer_list.CanFocus = true;
			this.button_edit_autogen_customer_list.Name = "button_edit_autogen_customer_list";
			this.button_edit_autogen_customer_list.UseUnderline = true;
			this.button_edit_autogen_customer_list.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.hbox7.Add(this.button_edit_autogen_customer_list);
			global::Gtk.Box.BoxChild w163 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button_edit_autogen_customer_list]));
			w163.Position = 2;
			w163.Expand = false;
			w163.Fill = false;
			this.vbox31.Add(this.hbox7);
			global::Gtk.Box.BoxChild w164 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox7]));
			w164.Position = 2;
			w164.Expand = false;
			w164.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.hbox71 = new global::Gtk.HBox();
			this.hbox71.Name = "hbox71";
			this.hbox71.Spacing = 6;
			// Container child hbox71.Gtk.Box+BoxChild
			this.label48 = new global::Gtk.Label();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString("特殊顾客数量:");
			this.hbox71.Add(this.label48);
			global::Gtk.Box.BoxChild w165 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.label48]));
			w165.Position = 0;
			w165.Expand = false;
			w165.Fill = false;
			// Container child hbox71.Gtk.Box+BoxChild
			this.text_autogen_specialnum = new global::Gtk.Entry();
			this.text_autogen_specialnum.WidthRequest = 50;
			this.text_autogen_specialnum.CanFocus = true;
			this.text_autogen_specialnum.Name = "text_autogen_specialnum";
			this.text_autogen_specialnum.IsEditable = true;
			this.hbox71.Add(this.text_autogen_specialnum);
			global::Gtk.Box.BoxChild w166 = ((global::Gtk.Box.BoxChild)(this.hbox71[this.text_autogen_specialnum]));
			w166.Position = 1;
			w166.Expand = false;
			this.vbox31.Add(this.hbox71);
			global::Gtk.Box.BoxChild w167 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.hbox71]));
			w167.Position = 3;
			w167.Expand = false;
			w167.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.frame_auto_requirements = new global::Gtk.Frame();
			this.frame_auto_requirements.Name = "frame_auto_requirements";
			this.frame_auto_requirements.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame_auto_requirements.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox75 = new global::Gtk.HBox();
			this.hbox75.Name = "hbox75";
			this.hbox75.Spacing = 6;
			// Container child hbox75.Gtk.Box+BoxChild
			this.check_autogen_random_customer = new global::Gtk.CheckButton();
			this.check_autogen_random_customer.CanFocus = true;
			this.check_autogen_random_customer.Name = "check_autogen_random_customer";
			this.check_autogen_random_customer.Label = global::Mono.Unix.Catalog.GetString("指定顾客");
			this.check_autogen_random_customer.DrawIndicator = true;
			this.check_autogen_random_customer.UseUnderline = true;
			this.hbox75.Add(this.check_autogen_random_customer);
			global::Gtk.Box.BoxChild w168 = ((global::Gtk.Box.BoxChild)(this.hbox75[this.check_autogen_random_customer]));
			w168.Position = 0;
			// Container child hbox75.Gtk.Box+BoxChild
			this.check_autogen_random_food = new global::Gtk.CheckButton();
			this.check_autogen_random_food.CanFocus = true;
			this.check_autogen_random_food.Name = "check_autogen_random_food";
			this.check_autogen_random_food.Label = global::Mono.Unix.Catalog.GetString("指定食物");
			this.check_autogen_random_food.DrawIndicator = true;
			this.check_autogen_random_food.UseUnderline = true;
			this.hbox75.Add(this.check_autogen_random_food);
			global::Gtk.Box.BoxChild w169 = ((global::Gtk.Box.BoxChild)(this.hbox75[this.check_autogen_random_food]));
			w169.Position = 1;
			this.vbox6.Add(this.hbox75);
			global::Gtk.Box.BoxChild w170 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox75]));
			w170.Position = 0;
			w170.Expand = false;
			w170.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.check_autogen_random_smile = new global::Gtk.CheckButton();
			this.check_autogen_random_smile.CanFocus = true;
			this.check_autogen_random_smile.Name = "check_autogen_random_smile";
			this.check_autogen_random_smile.Label = global::Mono.Unix.Catalog.GetString("指定笑脸");
			this.check_autogen_random_smile.DrawIndicator = true;
			this.check_autogen_random_smile.UseUnderline = true;
			this.hbox9.Add(this.check_autogen_random_smile);
			global::Gtk.Box.BoxChild w171 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.check_autogen_random_smile]));
			w171.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.check_autogen_any_customer = new global::Gtk.CheckButton();
			this.check_autogen_any_customer.CanFocus = true;
			this.check_autogen_any_customer.Name = "check_autogen_any_customer";
			this.check_autogen_any_customer.Label = global::Mono.Unix.Catalog.GetString("服务任意顾客总数");
			this.check_autogen_any_customer.DrawIndicator = true;
			this.check_autogen_any_customer.UseUnderline = true;
			this.hbox9.Add(this.check_autogen_any_customer);
			global::Gtk.Box.BoxChild w172 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.check_autogen_any_customer]));
			w172.Position = 1;
			this.vbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w173 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
			w173.Position = 1;
			w173.Expand = false;
			w173.Fill = false;
			this.GtkAlignment1.Add(this.vbox6);
			this.frame_auto_requirements.Add(this.GtkAlignment1);
			this.GtkLabel22 = new global::Gtk.Label();
			this.GtkLabel22.Name = "GtkLabel22";
			this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString("<b>过关条件</b>");
			this.GtkLabel22.UseMarkup = true;
			this.frame_auto_requirements.LabelWidget = this.GtkLabel22;
			this.vbox31.Add(this.frame_auto_requirements);
			global::Gtk.Box.BoxChild w176 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.frame_auto_requirements]));
			w176.Position = 4;
			w176.Expand = false;
			w176.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.vbuttonbox7 = new global::Gtk.VButtonBox();
			this.vbuttonbox7.Name = "vbuttonbox7";
			this.vbuttonbox7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
			this.btn_autogen_generate = new global::Gtk.Button();
			this.btn_autogen_generate.CanFocus = true;
			this.btn_autogen_generate.Name = "btn_autogen_generate";
			this.btn_autogen_generate.UseUnderline = true;
			this.btn_autogen_generate.Label = global::Mono.Unix.Catalog.GetString("生成关卡配置");
			this.vbuttonbox7.Add(this.btn_autogen_generate);
			global::Gtk.ButtonBox.ButtonBoxChild w177 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox7[this.btn_autogen_generate]));
			w177.Expand = false;
			w177.Fill = false;
			// Container child vbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
			this.button_autogen_requirements = new global::Gtk.Button();
			this.button_autogen_requirements.CanFocus = true;
			this.button_autogen_requirements.Name = "button_autogen_requirements";
			this.button_autogen_requirements.UseUnderline = true;
			this.button_autogen_requirements.Label = global::Mono.Unix.Catalog.GetString("重新生成过关条件");
			this.vbuttonbox7.Add(this.button_autogen_requirements);
			global::Gtk.ButtonBox.ButtonBoxChild w178 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox7[this.button_autogen_requirements]));
			w178.Position = 1;
			w178.Expand = false;
			w178.Fill = false;
			this.vbox31.Add(this.vbuttonbox7);
			global::Gtk.Box.BoxChild w179 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.vbuttonbox7]));
			w179.Position = 5;
			this.GtkAlignment7.Add(this.vbox31);
			this.frame_auto_gen.Add(this.GtkAlignment7);
			this.label_auto_gen1 = new global::Gtk.Label();
			this.label_auto_gen1.Name = "label_auto_gen1";
			this.label_auto_gen1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>自动生成配置</b>");
			this.label_auto_gen1.UseMarkup = true;
			this.frame_auto_gen.LabelWidget = this.label_auto_gen1;
			this.hbox20.Add(this.frame_auto_gen);
			global::Gtk.Box.BoxChild w182 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.frame_auto_gen]));
			w182.PackType = ((global::Gtk.PackType)(1));
			w182.Position = 4;
			w182.Expand = false;
			w182.Fill = false;
			w182.Padding = ((uint)(10));
			this.GtkAlignment3.Add(this.hbox20);
			this.frame_available_orders.Add(this.GtkAlignment3);
			this.Label_Available_Orders = new global::Gtk.Label();
			this.Label_Available_Orders.Name = "Label_Available_Orders";
			this.Label_Available_Orders.LabelProp = global::Mono.Unix.Catalog.GetString("<b>订单设置</b>");
			this.Label_Available_Orders.UseMarkup = true;
			this.frame_available_orders.LabelWidget = this.Label_Available_Orders;
			w1.Add(this.frame_available_orders);
			global::Gtk.Box.BoxChild w185 = ((global::Gtk.Box.BoxChild)(w1[this.frame_available_orders]));
			w185.Position = 2;
			w185.Padding = ((uint)(5));
			// Internal child LevelEditor.LevelDialog.ActionArea
			global::Gtk.HButtonBox w186 = this.ActionArea;
			w186.Name = "dialog1_ActionArea";
			w186.Spacing = 10;
			w186.BorderWidth = ((uint)(5));
			w186.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("关闭");
			this.AddActionWidget(this.buttonCancel, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w187 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w186[this.buttonCancel]));
			w187.Expand = false;
			w187.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("保存");
			w186.Add(this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w188 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w186[this.buttonOk]));
			w188.Position = 1;
			w188.Expand = false;
			w188.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1345;
			this.DefaultHeight = 938;
			this.Show();
			this.combobox_level_id.Changed += new global::System.EventHandler(this.OnComboboxLevelIdChanged);
			this.btn_reload_level.Clicked += new global::System.EventHandler(this.OnBtnReloadLevelClicked);
			this.btn_clear_data.Clicked += new global::System.EventHandler(this.OnBtnClearDataClicked);
			this.btn_config_secret_customers.Clicked += new global::System.EventHandler(this.OnBtnConfigSecretCustomersClicked);
			this.btn_config_level_requirements.Clicked += new global::System.EventHandler(this.OnBtnConfigLevelRequirementsClicked);
			this.button_edit_unlock_items.Clicked += new global::System.EventHandler(this.OnButtonEditUnlockItemsClicked);
			this.button_edit_rewards.Clicked += new global::System.EventHandler(this.OnButtonEditRewardsClicked);
			this.btn_config_level_tips.Clicked += new global::System.EventHandler(this.OnBtnConfigLevelTipsClicked);
			this.btn_add_order.Clicked += new global::System.EventHandler(this.OnBtnAddOrderClicked);
			this.btn_remove_order.Clicked += new global::System.EventHandler(this.OnBtnRemoveOrderClicked);
			this.button_order_up.Clicked += new global::System.EventHandler(this.OnButtonOrderUpClicked);
			this.button_order_down.Clicked += new global::System.EventHandler(this.OnButtonOrderDownClicked);
			this.button_normalize_weight.Clicked += new global::System.EventHandler(this.OnButtonNormalizeWeightClicked);
			this.button_edit_autogen_food_list.Clicked += new global::System.EventHandler(this.OnButtonEditAutogenFoodListClicked);
			this.button_edit_autogen_customer_list.Clicked += new global::System.EventHandler(this.OnButtonEditAutogenCustomerListClicked);
			this.btn_autogen_generate.Clicked += new global::System.EventHandler(this.OnBtnAutogenGenerateClicked);
			this.button_autogen_requirements.Clicked += new global::System.EventHandler(this.OnButtonAutogenRequirementsClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
