
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class NewOrderDialog
	{
		private global::Gtk.HBox hbox5;

		private global::Gtk.Frame frame9;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Image image_food;

		private global::Gtk.Label label_food_name;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Image image_customer;

		private global::Gtk.ComboBox combobox_customer;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Frame frame7;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entry_waittime;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label3;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Entry entry_tip;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entry_consider_time;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LevelEditor.NewOrderDialog
			this.Name = "LevelEditor.NewOrderDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("订单配置");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child LevelEditor.NewOrderDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame9.BorderWidth = ((uint)(5));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.image_food = new global::Gtk.Image();
			this.image_food.WidthRequest = 100;
			this.image_food.HeightRequest = 100;
			this.image_food.Name = "image_food";
			this.vbox11.Add(this.image_food);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.image_food]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label_food_name = new global::Gtk.Label();
			this.label_food_name.Name = "label_food_name";
			this.label_food_name.LabelProp = global::Mono.Unix.Catalog.GetString("食物名称");
			this.vbox11.Add(this.label_food_name);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label_food_name]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			this.GtkAlignment4.Add(this.vbox11);
			this.frame9.Add(this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>食物</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel4;
			this.hbox5.Add(this.frame9);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame9]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame5.BorderWidth = ((uint)(5));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.image_customer = new global::Gtk.Image();
			this.image_customer.WidthRequest = 100;
			this.image_customer.HeightRequest = 100;
			this.image_customer.Name = "image_customer";
			this.vbox7.Add(this.image_customer);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.image_customer]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(5));
			// Container child vbox7.Gtk.Box+BoxChild
			this.combobox_customer = global::Gtk.ComboBox.NewText();
			this.combobox_customer.Name = "combobox_customer";
			this.vbox7.Add(this.combobox_customer);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.combobox_customer]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.GtkAlignment2.Add(this.vbox7);
			this.frame5.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>选择顾客</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel2;
			this.hbox5.Add(this.frame5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame5]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame7.BorderWidth = ((uint)(5));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("等待时间：");
			this.hbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry_waittime = new global::Gtk.Entry();
			this.entry_waittime.WidthRequest = 88;
			this.entry_waittime.CanFocus = true;
			this.entry_waittime.Name = "entry_waittime";
			this.entry_waittime.IsEditable = true;
			this.entry_waittime.InvisibleChar = '●';
			this.hbox7.Add(this.entry_waittime);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry_waittime]));
			w13.Position = 1;
			w13.Expand = false;
			this.vbox8.Add(this.hbox7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox7]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("小费：");
			this.hbox9.Add(this.label3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label3]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(24));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.entry_tip = new global::Gtk.Entry();
			this.entry_tip.WidthRequest = 88;
			this.entry_tip.CanFocus = true;
			this.entry_tip.Name = "entry_tip";
			this.entry_tip.IsEditable = true;
			this.entry_tip.InvisibleChar = '●';
			this.alignment2.Add(this.entry_tip);
			this.hbox9.Add(this.alignment2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment2]));
			w17.Position = 1;
			w17.Expand = false;
			this.vbox8.Add(this.hbox9);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox9]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("考虑时间：");
			this.hbox11.Add(this.label5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label5]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry_consider_time = new global::Gtk.Entry();
			this.entry_consider_time.WidthRequest = 88;
			this.entry_consider_time.CanFocus = true;
			this.entry_consider_time.Name = "entry_consider_time";
			this.entry_consider_time.IsEditable = true;
			this.entry_consider_time.InvisibleChar = '●';
			this.hbox11.Add(this.entry_consider_time);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.entry_consider_time]));
			w20.Position = 1;
			w20.Expand = false;
			this.vbox8.Add(this.hbox11);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox11]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.GtkAlignment3.Add(this.vbox8);
			this.frame7.Add(this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>参数设定</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel3;
			this.hbox5.Add(this.frame7);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame7]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			w1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w1[this.hbox5]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Internal child LevelEditor.NewOrderDialog.ActionArea
			global::Gtk.HButtonBox w26 = this.ActionArea;
			w26.Name = "dialog1_ActionArea";
			w26.Spacing = 10;
			w26.BorderWidth = ((uint)(5));
			w26.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonCancel]));
			w27.Expand = false;
			w27.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonOk]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 454;
			this.DefaultHeight = 226;
			this.Show();
			this.combobox_customer.Changed += new global::System.EventHandler(this.OnComboboxCustomerChanged);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
