
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class OrderEditor
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview_foodlist;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview_orderlist;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button btn_add_order;

		private global::Gtk.Button btn_remove_order;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LevelEditor.OrderEditor
			this.Name = "LevelEditor.OrderEditor";
			this.Title = global::Mono.Unix.Catalog.GetString("订单编辑");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child LevelEditor.OrderEditor.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame1.BorderWidth = ((uint)(5));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview_foodlist = new global::Gtk.TreeView();
			this.treeview_foodlist.WidthRequest = 250;
			this.treeview_foodlist.CanFocus = true;
			this.treeview_foodlist.Name = "treeview_foodlist";
			this.GtkScrolledWindow.Add(this.treeview_foodlist);
			this.GtkAlignment2.Add(this.GtkScrolledWindow);
			this.frame1.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>食物列表</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.hbox3.Add(this.frame1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(2));
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame3.BorderWidth = ((uint)(5));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview_orderlist = new global::Gtk.TreeView();
			this.treeview_orderlist.WidthRequest = 400;
			this.treeview_orderlist.CanFocus = true;
			this.treeview_orderlist.Name = "treeview_orderlist";
			this.GtkScrolledWindow1.Add(this.treeview_orderlist);
			this.vbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
			w7.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btn_add_order = new global::Gtk.Button();
			this.btn_add_order.CanFocus = true;
			this.btn_add_order.Name = "btn_add_order";
			this.btn_add_order.UseUnderline = true;
			this.btn_add_order.Label = global::Mono.Unix.Catalog.GetString("+");
			this.hbuttonbox2.Add(this.btn_add_order);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btn_add_order]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btn_remove_order = new global::Gtk.Button();
			this.btn_remove_order.CanFocus = true;
			this.btn_remove_order.Name = "btn_remove_order";
			this.btn_remove_order.UseUnderline = true;
			this.btn_remove_order.Label = global::Mono.Unix.Catalog.GetString("-");
			this.hbuttonbox2.Add(this.btn_remove_order);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btn_remove_order]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add(this.hbuttonbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.GtkAlignment3.Add(this.vbox2);
			this.frame3.Add(this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>订单列表</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel3;
			this.hbox3.Add(this.frame3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame3]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(2));
			w1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1[this.hbox3]));
			w14.Position = 0;
			// Internal child LevelEditor.OrderEditor.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Name = "dialog1_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("关闭");
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonCancel]));
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanDefault = true;
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("保存");
			w15.Add(this.buttonSave);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonSave]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 750;
			this.DefaultHeight = 610;
			this.Show();
			this.treeview_foodlist.CursorChanged += new global::System.EventHandler(this.OnTreeviewFoodlistCursorChanged);
			this.btn_add_order.Clicked += new global::System.EventHandler(this.OnBtnAddOrderClicked);
			this.btn_remove_order.Clicked += new global::System.EventHandler(this.OnBtnRemoveOrderClicked);
			this.buttonSave.Clicked += new global::System.EventHandler(this.OnButtonSaveClicked);
		}
	}
}
