
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class FoodRequirementDialog
	{
		private global::Gtk.VBox dialog1_VBox1;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview_food_list;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.VButtonBox vbuttonbox1;

		private global::Gtk.Button button_add_food;

		private global::Gtk.Button button_remove_food;

		private global::Gtk.Frame frame8;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview_require_foods;

		private global::Gtk.Label GtkLabel6;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LevelEditor.FoodRequirementDialog
			this.Name = "LevelEditor.FoodRequirementDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("制作食物过关要求");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LevelEditor.FoodRequirementDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_VBox1 = new global::Gtk.VBox();
			this.dialog1_VBox1.Name = "dialog1_VBox1";
			this.dialog1_VBox1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame3.BorderWidth = ((uint)(5));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame6.BorderWidth = ((uint)(1));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview_food_list = new global::Gtk.TreeView();
			this.treeview_food_list.WidthRequest = 150;
			this.treeview_food_list.CanFocus = true;
			this.treeview_food_list.Name = "treeview_food_list";
			this.GtkScrolledWindow.Add(this.treeview_food_list);
			this.GtkAlignment3.Add(this.GtkScrolledWindow);
			this.frame6.Add(this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>食物列表</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel3;
			this.hbox9.Add(this.frame6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.frame6]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button_add_food = new global::Gtk.Button();
			this.button_add_food.CanFocus = true;
			this.button_add_food.Name = "button_add_food";
			this.button_add_food.UseUnderline = true;
			this.button_add_food.Label = global::Mono.Unix.Catalog.GetString(">>>>");
			this.vbuttonbox1.Add(this.button_add_food);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button_add_food]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button_remove_food = new global::Gtk.Button();
			this.button_remove_food.CanFocus = true;
			this.button_remove_food.Name = "button_remove_food";
			this.button_remove_food.UseUnderline = true;
			this.button_remove_food.Label = global::Mono.Unix.Catalog.GetString("<<<<");
			this.vbuttonbox1.Add(this.button_remove_food);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button_remove_food]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox9.Add(this.vbuttonbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbuttonbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame8.BorderWidth = ((uint)(1));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview_require_foods = new global::Gtk.TreeView();
			this.treeview_require_foods.WidthRequest = 250;
			this.treeview_require_foods.CanFocus = true;
			this.treeview_require_foods.Name = "treeview_require_foods";
			this.GtkScrolledWindow1.Add(this.treeview_require_foods);
			this.GtkAlignment4.Add(this.GtkScrolledWindow1);
			this.frame8.Add(this.GtkAlignment4);
			this.GtkLabel6 = new global::Gtk.Label();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>要求制作完成的食物</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel6;
			this.hbox9.Add(this.frame8);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.frame8]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.GtkAlignment2.Add(this.hbox9);
			this.frame3.Add(this.GtkAlignment2);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>选择食物</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel5;
			this.dialog1_VBox1.Add(this.frame3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1[this.frame3]));
			w15.Position = 0;
			w1.Add(this.dialog1_VBox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(w1[this.dialog1_VBox1]));
			w16.Position = 0;
			// Internal child LevelEditor.FoodRequirementDialog.ActionArea
			global::Gtk.HButtonBox w17 = this.ActionArea;
			w17.Name = "dialog1_ActionArea";
			w17.Spacing = 10;
			w17.BorderWidth = ((uint)(5));
			w17.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonCancel]));
			w18.Expand = false;
			w18.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonOk]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 584;
			this.DefaultHeight = 551;
			this.Show();
			this.button_add_food.Clicked += new global::System.EventHandler(this.OnButtonAddFoodClicked);
			this.button_remove_food.Clicked += new global::System.EventHandler(this.OnButtonRemoveFoodClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
