
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class RequirementEditDialog
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.CheckButton checkbutton_allow_burn;

		private global::Gtk.CheckButton checkbutton_allow_lost;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entry_smile_count;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entry_required_customers;

		private global::Gtk.Button button_edit_customers;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entry_required_foods;

		private global::Gtk.Button button_edit_foods;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LevelEditor.RequirementEditDialog
			this.Name = "LevelEditor.RequirementEditDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("过关条件编辑器");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LevelEditor.RequirementEditDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame1.BorderWidth = ((uint)(5));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkbutton_allow_burn = new global::Gtk.CheckButton();
			this.checkbutton_allow_burn.CanFocus = true;
			this.checkbutton_allow_burn.Name = "checkbutton_allow_burn";
			this.checkbutton_allow_burn.Label = global::Mono.Unix.Catalog.GetString("是否允许烧焦？");
			this.checkbutton_allow_burn.Active = true;
			this.checkbutton_allow_burn.DrawIndicator = true;
			this.checkbutton_allow_burn.UseUnderline = true;
			this.hbox1.Add(this.checkbutton_allow_burn);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.checkbutton_allow_burn]));
			w2.Position = 0;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.checkbutton_allow_lost = new global::Gtk.CheckButton();
			this.checkbutton_allow_lost.CanFocus = true;
			this.checkbutton_allow_lost.Name = "checkbutton_allow_lost";
			this.checkbutton_allow_lost.Label = global::Mono.Unix.Catalog.GetString("是否允许顾客流失？");
			this.checkbutton_allow_lost.Active = true;
			this.checkbutton_allow_lost.DrawIndicator = true;
			this.checkbutton_allow_lost.UseUnderline = true;
			this.vbox2.Add(this.checkbutton_allow_lost);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.checkbutton_allow_lost]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("收集笑脸数量：");
			this.hbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entry_smile_count = new global::Gtk.Entry();
			this.entry_smile_count.WidthRequest = 50;
			this.entry_smile_count.CanFocus = true;
			this.entry_smile_count.Name = "entry_smile_count";
			this.entry_smile_count.Text = global::Mono.Unix.Catalog.GetString("0");
			this.entry_smile_count.IsEditable = true;
			this.entry_smile_count.InvisibleChar = '●';
			this.hbox3.Add(this.entry_smile_count);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry_smile_count]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("服务顾客：");
			this.hbox5.Add(this.label5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label5]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry_required_customers = new global::Gtk.Entry();
			this.entry_required_customers.CanFocus = true;
			this.entry_required_customers.Name = "entry_required_customers";
			this.entry_required_customers.IsEditable = false;
			this.entry_required_customers.InvisibleChar = '●';
			this.hbox5.Add(this.entry_required_customers);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry_required_customers]));
			w9.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button_edit_customers = new global::Gtk.Button();
			this.button_edit_customers.CanFocus = true;
			this.button_edit_customers.Name = "button_edit_customers";
			this.button_edit_customers.UseUnderline = true;
			this.button_edit_customers.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.hbox5.Add(this.button_edit_customers);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button_edit_customers]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("制作食物：");
			this.hbox7.Add(this.label6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label6]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry_required_foods = new global::Gtk.Entry();
			this.entry_required_foods.CanFocus = true;
			this.entry_required_foods.Name = "entry_required_foods";
			this.entry_required_foods.IsEditable = false;
			this.entry_required_foods.InvisibleChar = '●';
			this.hbox7.Add(this.entry_required_foods);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry_required_foods]));
			w13.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button_edit_foods = new global::Gtk.Button();
			this.button_edit_foods.CanFocus = true;
			this.button_edit_foods.Name = "button_edit_foods";
			this.button_edit_foods.UseUnderline = true;
			this.button_edit_foods.Label = global::Mono.Unix.Catalog.GetString("修改");
			this.hbox7.Add(this.button_edit_foods);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button_edit_foods]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox2.Add(this.hbox7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.GtkAlignment2.Add(this.vbox2);
			this.frame1.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>过关条件</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			w1.Add(this.frame1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(w1[this.frame1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Internal child LevelEditor.RequirementEditDialog.ActionArea
			global::Gtk.HButtonBox w19 = this.ActionArea;
			w19.Name = "dialog1_ActionArea";
			w19.Spacing = 10;
			w19.BorderWidth = ((uint)(5));
			w19.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w19[this.buttonCancel]));
			w20.Expand = false;
			w20.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w19[this.buttonOk]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 352;
			this.DefaultHeight = 255;
			this.Show();
			this.entry_smile_count.TextInserted += new global::Gtk.TextInsertedHandler(this.OnEntrySmileCountTextInserted);
			this.button_edit_customers.Clicked += new global::System.EventHandler(this.OnButtonEditCustomersClicked);
			this.button_edit_foods.Clicked += new global::System.EventHandler(this.OnButtonEditFoodsClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
