
// This file has been generated by the GUI designer. Do not modify.
namespace LevelEditor
{
	public partial class SecretCustomerEditDialog
	{
		private global::Gtk.HBox hbox13;

		private global::Gtk.Frame frame7;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview_customer_list;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.VButtonBox vbuttonbox1;

		private global::Gtk.Button button_add_customer;

		private global::Gtk.Button button_remove_customer;

		private global::Gtk.Frame frame9;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview_secret_customers;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LevelEditor.SecretCustomerEditDialog
			this.Name = "LevelEditor.SecretCustomerEditDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("神秘顾客");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LevelEditor.SecretCustomerEditDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview_customer_list = new global::Gtk.TreeView();
			this.treeview_customer_list.WidthRequest = 150;
			this.treeview_customer_list.CanFocus = true;
			this.treeview_customer_list.Name = "treeview_customer_list";
			this.GtkScrolledWindow.Add(this.treeview_customer_list);
			this.GtkAlignment2.Add(this.GtkScrolledWindow);
			this.frame7.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>顾客列表</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel2;
			this.hbox13.Add(this.frame7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.frame7]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button_add_customer = new global::Gtk.Button();
			this.button_add_customer.CanFocus = true;
			this.button_add_customer.Name = "button_add_customer";
			this.button_add_customer.UseUnderline = true;
			this.button_add_customer.Label = global::Mono.Unix.Catalog.GetString(">>>>");
			this.vbuttonbox1.Add(this.button_add_customer);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button_add_customer]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button_remove_customer = new global::Gtk.Button();
			this.button_remove_customer.CanFocus = true;
			this.button_remove_customer.Name = "button_remove_customer";
			this.button_remove_customer.UseUnderline = true;
			this.button_remove_customer.Label = global::Mono.Unix.Catalog.GetString("<<<<");
			this.vbuttonbox1.Add(this.button_remove_customer);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button_remove_customer]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox13.Add(this.vbuttonbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.vbuttonbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview_secret_customers = new global::Gtk.TreeView();
			this.treeview_secret_customers.WidthRequest = 250;
			this.treeview_secret_customers.CanFocus = true;
			this.treeview_secret_customers.Name = "treeview_secret_customers";
			this.GtkScrolledWindow1.Add(this.treeview_secret_customers);
			this.GtkAlignment3.Add(this.GtkScrolledWindow1);
			this.frame9.Add(this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>神秘顾客</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel5;
			this.hbox13.Add(this.frame9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.frame9]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			w1.Add(this.hbox13);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1[this.hbox13]));
			w13.Position = 0;
			// Internal child LevelEditor.SecretCustomerEditDialog.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14[this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14[this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 548;
			this.DefaultHeight = 508;
			this.Show();
			this.button_add_customer.Clicked += new global::System.EventHandler(this.OnButtonAddCustomerClicked);
			this.button_remove_customer.Clicked += new global::System.EventHandler(this.OnButtonRemoveCustomerClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
